FROM python:3.8.12-buster

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1
ENV LANG C.UTF-8

RUN pip install pipenv \
    psycopg2-binary

WORKDIR /opt/api-deploy

ENV FLASK_APP=app.py
ENV FLASK_RUN_PORT=8000

COPY . .

RUN pipenv install --system --skip-lock

CMD flask run
