version: '3.9'

services:

  api:
    container_name: users-api
    image: users-flask-docker:latest
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      - "FLASK_RUN_HOST=0.0.0.0"
      - "FLASK_RUN_PORT=8000"
    ports:
      - "8000:8000"
    env_file: .env
    working_dir: /opt/api-deploy/api
    volumes:
      - ./:/opt/api-deploy/api
    depends_on:
      - db
      - cache

  db:
    image: postgres:13
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  pgdata:
  cache:
