version: '3.4'

services:

  api:
    image: users-flask-docker:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "PORT=8000"
    ports:
      - "8000:8000"
    env_file: .env
    working_dir: /opt/api-deploy
