version: '3.9'

services:

  api:
    container_name: users-api
    image: users-flask-docker:latest
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      - "FLASK_RUN_HOST=0.0.0.0"
      - "FLASK_RUN_PORT=8000"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres"
    ports:
      - "8000:8000"
    env_file: .env
    working_dir: /opt/api-deploy
    volumes:
      - ./:/opt/api-deploy
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
